<a href="https://colab.research.google.com/github/nightitachi/Block-Notes/blob/main/Store_Sales_Time_Series_Forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Handling Data

In [ ]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
stores = pd.read_csv('stores.csv')
oil = pd.read_csv('oil.csv')
transactions = pd.read_csv('transactions.csv')
holidays = pd.read_csv('holidays_events.csv')

# Exploring the Data

In [ ]:
train.head()

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [ ]:
stores.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [ ]:
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [ ]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

In [ ]:
train.isnull().sum()

id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

In [ ]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   object
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [ ]:
oil.shape

(1218, 2)

In [ ]:
oil.isnull().sum()

date           0
dcoilwtico    43
dtype: int64

In [ ]:
oil['dcoilwtico'].value_counts()

dcoilwtico
47.72    4
47.65    4
96.44    4
60.01    4
46.02    4
        ..
94.35    1
96.40    1
93.97    1
95.39    1
47.26    1
Name: count, Length: 998, dtype: int64

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [ ]:
transactions.isnull().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [ ]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     object
 2   state      54 non-null     object
 3   type       54 non-null     object
 4   cluster    54 non-null     int64
dtypes: int64(2), object(3)
memory usage: 2.2+ KB

In [ ]:
stores.isnull().sum()

store_nbr    0
city         0
state        0
type         0
cluster      0
dtype: int64

# Cleaning Data

oil Data

In [ ]:
oil['dcoilwtico'].fillna(oil['dcoilwtico'].median(), inplace=True)

<ipython-input-122-1bf201594d61>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  oil['dcoilwtico'].fillna(oil['dcoilwtico'].median(), inplace=True)

In [ ]:
oil.isnull().sum()

date          0
dcoilwtico    0
dtype: int64

Train Data

In [ ]:
train['store_nbr'] = train['store_nbr'].fillna(0)

In [ ]:
train['family'] = train['family'].fillna(0)
train['sales'] = train['sales'].fillna(0)
train['onpromotion'] = train['onpromotion'].fillna(0)

In [ ]:
train.isnull().sum()

id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

In [ ]:
holidays.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [ ]:
holidays.isnull().sum()

date           0
type           0
locale         0
locale_name    0
description    0
transferred    0
dtype: int64

In [ ]:
holidays.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    object
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), object(5)
memory usage: 14.1+ KB

In [ ]:
oil['date'] = pd.to_datetime(oil['date'])
test['date'] = pd.to_datetime(test['date'])
transactions['date'] = pd.to_datetime(transactions['date'])
holidays['date'] = pd.to_datetime(holidays['date'])
train = train[train['date'] > '2013-01-01']

In [ ]:
train.info()
test.info()
print('*************************')
oil.info()
print('*************************')
holidays.info()
holidays
oil
train
transactions

<class 'pandas.core.frame.DataFrame'>
Index: 2999106 entries, 1782 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 160.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28512 entries, 0 to 28511
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           28512 non-null  int64
 1   date         28512 non-null  datetime64[ns]
 2   store_nbr    28512 non-null  int64
 3   family       28512 non-null  object
 4   onpromotion  28512 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB
*************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1218 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB
*************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    datetime64[ns]
 1   type         350 non-null    object
 2   locale       350 non-null    object
 3   locale_name  350 non-null    object
 4   description  350 non-null    object
 5   transferred  350 non-null    bool
dtypes: bool(1), datetime64[ns](1), object(4)
memory usage: 14.1+ KB

            date  store_nbr  transactions
0     2013-01-01         25           770
1     2013-01-02          1          2111
2     2013-01-02          2          2358
3     2013-01-02          3          3487
4     2013-01-02          4          1922
...          ...        ...           ...
83483 2017-08-15         50          2804
83484 2017-08-15         51          1573
83485 2017-08-15         52          2255
83486 2017-08-15         53           932
83487 2017-08-15         54           802

[83488 rows x 3 columns]

In [ ]:
def processed_data(df: pd.DataFrame, is_test=False):
    col_train = ['date', 'store_nbr', 'onpromotion', 'family', 'id', 'sales']
    col_test = ['date', 'family', 'store_nbr', 'onpromotion', 'id']
    col_holidays = ['date', 'type', 'transferred']

    if is_test:
        col_df = col_test
    else:
        col_df = col_train

    # Ensure 'date' columns are of datetime type
    df['date'] = pd.to_datetime(df['date'])
    oil['date'] = pd.to_datetime(oil['date'])
    holidays['date'] = pd.to_datetime(holidays['date'])

    # Merging data
    df = df[col_df].merge(oil, 'left', 'date').merge(holidays[col_holidays], 'left', 'date').rename(
        columns={'type': 'day_type', 'dcoilwtico': 'crude_price'})

    df['day_type'] = df['day_type'].fillna('Work Day')
    df['transferred'] = df['transferred'].fillna(False)

    df['is_holiday'] = np.where(
        (df['day_type'] == 'Work Day'), 0,
        np.where(
            (df['day_type'].isin(['Holiday', 'Additional', 'Event', 'Transfer', 'Bridge'])) &
            (df['transferred'] == False),
            1,
            0
        )
    )

    # Fixing onpromotion column values
    df['onpromotion'] = np.where(df['onpromotion'] == 0.0, 0, 1)

    df['day_number'] = pd.factorize(df['date'])[0] + 1
    df['day_type'] = df.drop(['transferred', 'day_type', 'date'], axis=1)
    df['crude_price'] = df['crude_price'].fillna(method='ffill')

    # Encoding the 'family' column
    family_encoding = pd.get_dummies(df['family'], prefix='family').astype(int)
    df = pd.concat([df, family_encoding], axis=1)
    df = df.drop(['family'], axis=1)

    # Drop missing values
    df = df.dropna()

    return df

df_train = processed_data(train)
df_test = processed_data(test, is_test=True)

<ipython-input-135-56c47f3abd4b>:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['transferred'] = df['transferred'].fillna(False)
<ipython-input-135-56c47f3abd4b>:43: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['crude_price'] = df['crude_price'].fillna(method='ffill')
<ipython-input-135-56c47f3abd4b>:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['transferred'] = df['transferred'].fillna(False)
<ipython-input-135-56c47f3abd4b>:43: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['crude_price'] = df['crude_price'].fillna(method='ffill')

In [ ]:
df_train = processed_data(train)
df_test = processed_data(test , is_test=True)

ValueError: You are trying to merge on object and datetime64[ns] columns for key 'date'. If you wish to proceed you should use pd.concat